/**
 * 
 */
package com.itom.rest;

import com.itom.base.BaseClass;;

/**
 * @author prabhudatta.choudhur
 *
 */
public interface APIUri {

	public String SEARCH_ALERT_API = "/tenants/{tenantId}/alerts/search";
	public String HEAL_ALERTS = "/tenants/{tenantId}/alerts/heal?extAlertIds={extAlertIds}";
	public String baseUri = (String) BaseClass.getConstant("opsRamp_web_url");
	public String DOWNLOAD_WINDOWS_AGENT="/tenants/{clientId}/agents/windows";
	public String apibaseUri = (String) BaseClass.getConstant("opsRamp_web_url")+"/api/v2";
	public String basicUri=(String) BaseClass.getConstant("opsRamp_web_url")+"/api";
	public String accessToken = "/auth/oauth/token";
	public String GET_ALERT_TECHNOLOGIES_URI = "/cfg/alertTechnologies";
	public String GET_ALERTS_MINIMAL = "/tenants/{varId}/clients/minimal";
	public String GET_MINIMAL_DEVICES_URI = "/tenants/{clientId}/devices/minimal";
	public String SEARCH_DEVICES_BY_TENANT = "/tenants/{tenantId}/devices/search";
	public String GET_INCIDENT ="/tenants/{clientId}/incidents/{incidentId}";
	public String CREATE_INCIDENT = "/tenants/{clientId}/incidents";
	public String GET_INCIDENT_CUSTOM_FORM = "/tenants/{clientId}/incidents/customForm";
	public String GET_MINIMAL_USER = "/tenants/{orgId}/users/minimal";
	public String GET_CATEGORIES = "/tenants/{clientId}/{ticketType}/categories/{parentCategoryId}";
	public String GET_SUBCATEGORIES = "/tenants/{clientId}/{ticketType}/categories/{parentCategoryId}";
	public String GET_USER_GROUPS = "/tenants/{orgId}/userGroups/{userGroupId}";
	public String GET_ALERT_OCCURENCES = "/tenants/{clientId}/alerts/{alertId}/occurrences";
	public String CREATE_DEVICE =  "/tenants/{clientId}/devices";
	public String GET_DEVICE = "/tenants/{clientId}/devices/{deviceId}";
	public String GET_URGENCIES = "/tenants/{clientId}/incidents/urgencies";
	public String GET_BUSINESS_IMPACTS = "/tenants/{clientId}/incidents/businessImpacts";
	public String ADD_RESPONSE_TO_INCIDENT = "/tenants/{clientId}/incidents/{incidentId}/responses";
	public String DOWNLOAD_RESPONSE_ATTACHMENT = "/tenants/{clientId}/incidents/{incidentId}/responses/{responseId}/resources/{resourceId}";
	public String SEARCH_INCIDENT = "/tenants/{clientId}/incidents/search?";
	public String GET_INCIDENT_RESPONSE_SEARCH = "/tenants/{clientId}/incidents/{incidentId}/responses/search";
	public String GET_STATUS_CHANGE = "/tenants/{clientId}/{ticketType}/statusReasons";
	public String CREATE_PROBLEM = "/tenants/{clientId}/problems";
	public String CLOSE_INCIDENT = "/tenants/{clientId}/incidents/{incidentId}/close";
	public String GET_PROBLEM = "/tenants/{clientId}/problems/{problemId}";
	public String ADD_RESPONSE_TO_PROBLEM = "/tenants/{clientId}/problems/{problemId}/responses";
	public String GET_RESPONSES_FROM_PROBLEM = "/tenants/{clientId}/problems/{problemId}/responses/search";
	public String CLOSE_PROBLEM = "/tenants/{clientId}/problems/{problemId}/close";
	public String GET_DEVICE_APPLICATIONS = "/tenants/{clientId}/devices/{deviceId}/applications";
	public String GET_DEVICE_AVAILABILITY = "/tenants/{clientId}/resources/type/{resourceType}/{resourceUUID}/availability";
	public String GET_DEVICE_BY_DEVICE_GROUPID = "/tenants/{clientId}/deviceGroupDevices/{deviceGroupId}";
	public String GET_MINIMAL_DEVICE_TYPES = "/tenants/{clientId}/deviceTypes/minimal";
	public String GET_RESOURCE = "/tenants/{clientId}/resources/{resourceId}";
	public String SEARCH_RESOURCES = "/tenants/{tenantId}/resources/search";
	public String UNMANAGE_DEVICE = "/tenants/{clientId}/devices/{deviceId}/unmanage";
	public String MANAGE_DEVICE = "/tenants/{clientId}/devices/{deviceId}/manage";
	public String UPDATE_DEVICE = "/tenants/{tenantId}/devices/{deviceId}";
	public String GET_JOBS_TYPES = "/tenants/{clientId}/jobs/types";
	public String GET_JOB = "/tenants/{clientId}/jobs/{id}";
	public String GET_JOBS = "/tenants/{clientId}/jobs";
	public String UNASSIGN_DEVICES = "/tenants/{clientId}/jobs/{id}/devices";
	public String ASSIGN_DEVICES_PATH_CONFIG = "/tenants/{tenantId}/patches/configurations/{id}/devices";
	public String CREATE_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations";
	public String GET_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/{id}";
	public String RUN_JOB = "/tenants/{clientId}/jobs/{id}/run";
	public String RUN_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/{id}/run"; 
	public String SEARCH_JOBS = "/tenants/{clientId}/jobs/search";
	public String SEARCH_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/search";
	public String GET_METRIC_TYPE = "/metric/tenants/{tenantId}/metrics/{metric}/metricType";
	public String GET_METRIC_ON_RESOURCE = "/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/metrics";
	public String SAVE_METRIC_ON_RESOURCE = "/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/metric"; 
	public String GET_METRIC_BY_METRIC_ON_RESOURCE = "/metric/search?tenant={tenantId}&rtype={rtype}&resource={resource}&metricGroup={metricGrp}&metric={metric}&startTime={startTime}&endTime={endTime}";
	public String CREATE_METRIC_TYPE = "/metric/tenants/{tenantId}/metrictype";
	public String CREATE_SERVICE_REQUEST = "/tenants/{clientId}/serviceRequests";
	public String ADD_RESPONSE = "/tenants/{clientId}/serviceRequests/{serviceRequestId}/responses";
	public String GET_CUSTOM_FIELD = "/tenants/{tenantId}/customFields/{classCode}";
	public String GET_RESPONSES = "/tenants/{clientId}/serviceRequests/{serviceRequestId}/responses/search";
	public String GET_SERVICE_REQUEST = "/tenants/{clientId}/serviceRequests/{serviceRequestId}";
	public String SEARCH_SERVICE_REQUESTS = "/tenants/{clientId}/serviceRequests/search";
	public String CLOSE_SERVICE_REQUEST = "/tenants/{clientId}/serviceRequests/{serviceRequestId}/close";
	public String CREATE_TASK = "/tenants/{clientId}/tasks";
	public String SEARCH_TASK = "/tenants/{clientId}/tasks/search";
	public String UPDATE_TASK = "/tenants/{clientId}/tasks/{taskId}";
	public String GET_RESPONSE_TASK = "/tenants/{clientId}/tasks/{taskId}/responses/search";
	public String CLOSE_TASK = "/tenants/{clientId}/tasks/{taskId}/close";
	public String ADD_RESPONSE_TASK = "/tenants/{clientId}/tasks/{taskId}/responses";
	public String CREATE_TIMEBOUND_REQUEST= "/tenants/{clientId}/timeBoundRequests";
	public String GET_PARTNER = "/tenants/{tenantId}/";
	public String SEARCH_TIMEBOUND_REQUESTS = "/tenants/{clientId}/timeBoundRequests/search";
	public String GET_TIMEBOUND_REQUEST = "/tenants/{clientId}/timeBoundRequests/{timeBoundRequestId}";
	public String GET_RESPONSE_TIMEBOUND_REQUESTS = "/tenants/{clientId}/timeBoundRequests/{timeBountRequestId}/responses/search";
	public String ADD_RESPONSE_TIMEBOUND_REQUEST = "/tenants/{clientId}/timeBoundRequests/{timeBoundRequestId}/responses";
	public String CLOSE_TIMEBOUND_REQUEST = "/tenants/{clientId}/timeBoundRequests/{timeBoundRequestId}/close";
	public String CREATE_CLIENT = "/tenants/{tenantId}/clients";
	public String DE_ACTIVATE_CLIENT = "/tenants/{tenantId}/clients/{clientId}/{action}";
	public String GET_CLIENT = "/tenants/{tenantId}/clients/{clientId}";
	public String SEARCH_CLIENT = "/tenants/{tenantId}/clients/search";
	public String CREATE_SHIFT_SCHEDULE = "/tenants/{tenantId}/shiftSchedules";
	public String GET_SHIFT_SCHEDULE = "/tenants/{tenantId}/shiftSchedules/{shiftScheduleId}";
	public String GET_PERMISSION = "/tenants/{tenantId}/permissionSets";
	public String CREATE_ROLE = "/tenants/{tenantId}/roles";
	public String GET_USER = "/tenants/{tenantId}/users/{userId}";
	public String SEARCH_ROLE = "/tenants/{tenantId}/roles/search";
	public String DELETE_ROLE = "/tenants/{tenantId}/roles/{roleId}";
	public String CREATE_PARTNER = "/serviceProvider/partners";
	public String GET_CHANNEL = "/cfg/tenants/channels";
	public String IN_ACTIVE_PARTNER = "/serviceProvider/partners/{id}/{action}";
	public String GLOBAL_SEARCH_PARTNERS="/serviceProvider/partners/search?pageSize:{pageSize}&queryString={queryString}";
	public String SEARCH_PARTNERS = "/tenants/search?pageSize:{pageSize}&queryString={queryString}";
	public String GLOBAL_SEARCH_USERS="/serviceProvider/users/search?pageSize:{pageSize}&queryString={queryString}";
	public String UPDATE_PARTNER = "/serviceProvider/partners/{tenantId}";
	public String CREATE_USER_GROUPS = "/tenants/{tenantId}/userGroups";
	public String CREATE_SCIM_USER_GROUPS="/integrations/tenants/{tenantId}/scim/Groups";
	public String GET_SCIM_GROUPS="/integrations/tenants/{tenantId}/scim/Groups/{groupId}";
	public String SEARCH_SCIM_GROUPS="/integrations/tenants/{tenantId}/scim/Groups/{groupId}";
	public String UPDATE_SCIM_GROUPS="/integrations/tenants/{tenantId}/scim/Groups/{groupId}";
	public String DELETE_SCIM_GROUPS="/integrations/tenants/{tenantId}/scim/Groups/{groupId}";
	public String ASSIGN_SCIMUSER_TO_SCIMUSERGROUP="/integrations/tenants/{tenantId}/scim/Groups/{groupId}";
	public String UNASSIGN_SCIMUSER_FROM_SCIMUSERGROUP="/integrations/tenants/{tenantId}/scim/Groups/{groupId}";
	public String DELETE_USER_GROUP = "/tenants/{tenantId}/userGroups/{userGroupId}";
	public String ADD_USER_TO_USER_GROUPS = "/tenants/{tenantId}/userGroups/{userGroupId}/users";
	public String CREATE_USER = "/tenants/{orgId}/users";
	public String CREATE_SCIM_USER="/integrations/tenants/{tenantId}/scim/Users";
	public String GET_SCIM_USER="/integrations/tenants/{tenantId}/scim/Users/{userId}";
	public String SEARCH_SCIM_USER="/integrations/tenants/{tenantId}/scim/Users";
	public String UPDATE_SCIM_USER="/integrations/tenants/{tenantId}/scim/Users/{userId}";
	public String PATCH_SCIM_USER="/integrations/tenants/{tenantId}/scim/Users/{userId}";
	public String DEACTIVATE_SCIM_USER="/integrations/tenants/{tenantId}/scim/Users/{userId}";
	public String UPDATE_USER="/tenants/{orgId}/users/{userId}";
	public String CHANGE_USER_PASSWORD = "/tenants/{orgId}/users/{userId}/changePassword";
	public String DEACTIVATE_USER="/tenants/{orgId}/users/{userId}/{action}";
	public String SEARCH_USER = "/tenants/{tenantId}/users/search";
	public String CREATE_ROASTER = "/tenants/{tenantId}/rosters";
	public String DELETE_ROASTER = "/tenants/{tenantId}/rosters/{id}";
	public String SEARCH_ROASTER = "/tenants/{tenantId}/rosters/search?pageNo={pageNo}&pageSize={pageSize}&queryString={queryString}";
	public String CHANGE_STATUS_ALERT_CORELATION_POLICY ="/tenants/{clientId}/policies/inferenceModel/{correlationId}/{status}";
	public String CREATE_INTEGRATION = "/solutionProvider/integrations";
	public String CREATE_INTEGRATION_EVENT="/tenants/{clientId}/integrations/installed/{installedIntgId}/event";
	public String INSTALL_INTEGRATION = "/tenants/{clientId}/integrations/install/{intgId}";
	public String SEARCH_INTEGRATION = "/tenants/{clientId}/integrations/available/search";
	public String SEARCH_INSTALLED_INTEGRATIONS = "/tenants/{clientId}/integrations/installed/search";
	public String INSTALL_INTG = "/tenants/{tenantId}/integrations/install/{intgId}";
	public String INTG_GET_MAP_PROPS = "/tenants/{tenantId}/integrations/available/{intgId}/mappingAttr/{entityType}";
	public String INTG_SAVE_ACTY = "/audit/intgActivity";
	public String GET_INTG_ACTY = "/audit/intgActivity/query";
	public String GET_INTG_ACTY_CNT = "/audit/intgActivity/count";
	public String SEARCH_INETEGRATION_RESOURCE = "/tenants/{tenantId}/integrations/installed/{id}/resources/{track}/search";
	public String GET_INTEGRATION_MAPPINGS = "/tenants/{clientId}/integrations/installed/{installedIntgId}/mappingAttr";
	public String GET_INT_EVENT_PLACE_HOLDERS = "/tenants/{tenantId}/integrations/events/placeHolders/{id}";
	public String GET_INTEGRATION_EVENT = "/tenants/{clientId}/integrations/installed/{installedIntgId}/event/{eventId}";
	public String GET_INTEGRATION_ACTIVITY = "/tenants/{clientId}/integrations/activity";
	public String GET_INTEGRATION_MAPPABLE_PROPERTIES = "/tenants/{clientId}/integrations/available/{intgId}/mappingAttr/{entityType}";
	public String GET_INSTALLED_INTEGRATION = "/tenants/{clientId}/integrations/installed/{id}";
	public String GET_INSTALLED_INTEGRATION_EVENTS = "/tenants/{clientId}/integrations/installed/{installedIntgId}/events";
	public String GET_CONFIG_EMAIL_PROPERTIES = "/tenants/{clientId}/integrations/available/{intgId}/emailProps/{entityType}";
	public String CHANGE_STATUS_INSTALLED_INTEGRATION = "/tenants/{tenantId}/integrations/installed/{id}/{status}";
	public String DEACTIVATE_INTEGRATION_EVENT = "/tenants/{clientId}/integrations/installed/{installedIntgId}/event/{eventId}/deactivate";
	public String CREATE_INSTALLED_INTEGRATION_BASE_NOTIFIER = "/tenants/{tenantId}/integrations/installed/{id}/notifier";
	public String DELETE_INTEGRATION_EVENT = "/tenants/{clientId}/integrations/installed/{installedIntgId}/deleteEvent/{eventId}";
	public String CREATE_INSTALLED_INTEGRATION_MAPPING = "/tenants/{tenantId}/integrations/installed/{id}/mappingAttr";
	public String CREATE_INBOUND_AUTHENTICATION = "/tenants/{tenantId}/integrations/installed/{id}/inbound/authentication";
	public String CREATE_CHANGE_REQUESTS = "/tenants/{clientId}/changeRequests";
	public String SEARCH_CHANGE_REQUESTS = "/tenants/{clientId}/changeRequests/search";
	public String GET_COUNTRIES = "/cfg/countries";
	public String GET_DEVICE_TYPES = "/cfg/devices/types";
	public String GET_NOCS = "/cfg/tenants/nocs";
	public String GET_TIMEZONES = "/cfg/timezones";
	public String ASSIGN_CHILDS = "/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs";
	public String GET_ROOT_DEVICE_GROUPS = "/tenants/{clientId}/deviceGroups/search";
	public String GET_CONSOLE_ACCESS_HISTORY = "/tenants/{clientId}/devices/auditRecordings/search";
	public String GET_DEVICE_RECORDINGS = "/tenants/{clientId}/devices/{deviceId}/auditRecordings/search";
	public String GET_RESOURCE_AUDIT_ACTIVITIES = "/tenants/{clientId}/activities/resources/search";
	public String GET_TICKET_RECORDINGS = "/tenants/{clientId}/tickets/{ticketId}/auditRecordings/search";
	public String CREATE_MANAGEMENT_POLICIES = "/tenants/{clientId}/policies/management";
	public String DELETE_MANAGEMENT_POLICIES = "/tenants/{clientId}/policies/management/{deviceManagementPolicyId}";
	public String SEARCH_MANAGEMENT_POLICIES = "/tenants/{clientId}/policies/management/search";
	public String INTG_SAVE_SYS_EVENT = "/audit/sysEvent";
	public String GET_INTG_SYS_EVENT = "/audit/sysEvent/query";
	public String GET_INTG_SYS_EVENT_CNT = "/audit/sysEvent/count";
	public String CREATE_MANAGEMENT_PROFILES="/tenants/{clientId}/managementProfiles";
	public String SEARCH_MANAGEMENT_PROFILES = "/tenants/{clientId}/managementProfiles/search";
	public String DELETE_MANAGEMENT_PROFILES = "/tenants/{clientId}/managementProfiles/{id}";
	public String CREATE_SCHEDULE_MAINTENACE="/tenants/{clientId}/scheduleMaintenances";
	public String SEARCH_SCHEDULE_MAINTENANCE="/tenants/{clientId}/scheduleMaintenances/search";
	public String DELETE_SCHEDULE_MAINTENANCE="/tenants/{tenantId}/scheduleMaintenances/{id}";
	public String END_SCHEDULE_MAINTENANCE="/tenants/{tenantId}/scheduleMaintenances/{id}/end";
	public String SUSPEND_SCHEDULE_MAINTENANCE="/tenants/{tenantId}/scheduleMaintenances/{id}/suspend";
	public String RESUME_SCHEDULE_MAINTENANCE="/tenants/{tenantId}/scheduleMaintenances/{id}/resume";
	public String CREATE_SERVICE_GROUPS="/tenants/{clientId}/policies/serviceGroups";
	public String SEARCH_SERVICE_GROUPS="/tenants/{clientId}/policies/serviceGroups/search?name={name}&pageNo={pageNo}&pageSize={pageSize}";
	public String GET_MINIMAL_SERVICE_GROUPS="/tenants/{clientId}/serviceGroups/minimal";
	public String GET_SERVICE_GROUP="/tenants/{clientId}/policies/serviceGroups/{serviceGroupId}";
	public String CREATE_SITE="/tenants/{clientId}/sites";
	public String SEARCH_SITE="/tenants/{clientId}/sites/search";
	public String GET_MINIMAL_SITES="/tenants/{clientId}/sites/minimal";
	public String GET_SITE="/tenants/{clientId}/sites/{siteId}";
	public String AWS_INTEGRATION="/tenants/{clientId}/integrations/install/AWS";
	public String AZURE_INTEGRATION="/tenants/{clientId}/integrations/install/AZURE";
	public String GOOGLE_INTEGRATION="/tenants/{clientId}/integrations/install/GOOGLE";
	public String INSTALL_KUBERNETS_INTEGRATION ="/tenants/{clientId}/integrations/install/KUBERNETES";
	public String SEARCH_DISCOVERY_PROFILE="/tenants/{tenantId}/policies/discovery/search?name={discoveryprofilename}";
	public String DELETE_DISCOVERY_PROFILE="/tenants/{clientId}/policies/discovery/{discoveryId}";
	public String GET_DISCOVERY_PROFILE="/tenants/{tenantId}/policies/discovery/";
	public String RESCAN_DISCOVERY_PROFILE="/tenants/{clientId}/policies/discovery/action/scan/{discoveryProfileId}";
	public String GET_ALERT_COUNT="/alerts/count/alertsCount";
	public String GET_LATEST_ALERTSTATE_OF_EACH_METRIC="/alerts/latestAlertStateOfMetric/rtypes/{rtype}/resources/{resource}/metrics/{metric}";
	public String GET_ALERT_LATEST_STATE="/alerts/latestAlertState/rtypes/{rtype}/resources/{resource}/metrics/{metric}";
	public String GET_LIST_OF_ALERTS="/alerts/search";
	public String GET_TICKET_COUNT="/alerts/count/ticketsCount";
	public String UPDATE_TICKET_STATUS="/tenants/{clientId}/alerts/ticket/{ticketId}/status/{status}";
	public String GET_TOP_METRICS="/tenants/{clientId}/metrics/top?duration={duration}&metrics={metricnames}";
	public String GET_AVAILABLE_METRICS_BY_RESOURCE="/metric/tenants/{tenant}/rtypes/{rtype}/resources/{resource}";
	public String SAVE_METRICS_ON_DEVICE="/metric/tenants/{tenantUid}/devices/{deviceUid}/metric";
	public String GET_TOP_METRICS_WITH_QUERY ="/topmetric/query?tenant={clientId}&duration={duration}&metrics={metricnames}";
    public String LATEST_METRICS_BY_METRICID ="/metric/tenants/{tenant}/rtypes/{rtype}/resources/{resource}/mids/{mid}";
    public String CHANGE_METRIC_TYPES="/metric/entity/metric/action/move/oldmid/{oldmid}/newmid/{newmid}";
    public String GET_AVAILABLE_METRICS_BY_METRIC_GROUP="/metric/tenants/{clientId}/metricGroups/{metricGroup}";
	public String INSTALL_INTEGRATION1="/tenants/{tenantId}/integrations/install/{id}";
	public String INSTALL_AND_CONFIGURE_AWSSUPPORT="/tenants/{clientId}/integrations/install/AWSSUPPORT";
	public String UNINSTALL_INTEGRATION="/tenants/{clientId}/integrations/installed/{installedIntgId}";
	public String CREATE_AGENT_DEVICE="/activate";
	public String DOWNLOAD_GO_AGENT="/tenants/{clientId}/agents/{platform}/download/{fileName}";
	public String GO_AGENT_INFO="/tenants/{clientId}/agents/{platform}/info";
	public String DOWNLOAD_LINUX_PATCH="/agents/{resourceUUID}/patches/{patchVersion}/download";
	public String GET_MODULE_INFORMATION="/agents/{resourceUUID}/moduleInfo";
	public String GET_AGENT_CONNECTION_NODE_DETAILS="/connectionNode/{resourceUUID}";
	public String GET_PATCH_INFORMATION="/agents/{resourceUUID}/patchInfo";
	public String DOWNLOAD_WINDOWS_PATCH_MODULE="/agents/{resourceUUID}/module/{moduleFileName}/{moduleVersion}/download";
	public String PLUGIN_CONFIGS="/tenants/{clientId}/plugins/{appUID}/config";
	public String PLUGIN_INFO="/agents/{resourceUUID}/pluginInfo/{pluginName}";
	public String GET_AUDIT_ACTIVITY="/audit/activity/query";
	public String GET_AUDIT_ACTIVITY_COUNT="/audit/activity/count";
	public String SAVE_AUDIT_ACTIVITY="/audit/activity";
	public String CREATE_METRICS="/metricstore/metrics";
	public String CREATE_RESOURCE_MONITORS="/tenants/{tenantId}/resourceMonitors";
	public String CREATE_CATEGORY="/tenants/{tenantId}/rba/categories";
	public String CREATE_SCRIPT="/tenants/{tenantId}/rba/categories/{id}/scripts";
	public String DELETE_SCRIPT="/tenants/{tenantId}/rba/categories/{id}/scripts/{scriptId}";
	public String GET_MACROS="/rba/scripts/macros";
	public String GET_OUTPUT_LOGS="/tenants/{tenantId}/rba/scripts/{id}/logs";
	public String CREATE_CATEGORIES="/tenants/{clientId}/serviceCatalogs/categories";
	public String DELETE_CATEGORY="/tenants/{tenantId}/serviceCatalogs/categories/{id}";
	public String SERVICE_CATALOG_GET_CATEGORIES="/tenants/{clientId}/serviceCatalogs/categories/search";
	public String GET_CATALOG_ITEM="/tenants/{tenantId}/serviceCatalogs/items/{id}";
	public String ORDER_CATALOG_ITEM="/tenants/{tenantId}/serviceCatalogs/items/{id}/order";
	public String CREATE_SERVICEDESK_NOTES="/tenants/{clientId}/{ticketType}/{ticketId}/notes";
	public String DELETE_SERVICEDESK_NOTES="/tenants/{clientId}/{ticketType}/{ticketId}/notes/{noteId}";
	public String GET_SLA_POLICY="/tenants/{clientId}/{ticketType}/slaPolicies/{parentCategoryId}";
	public String SEARCH_SLA_POLICY="/tenants/{clientId}/{ticketType}/slaPolicies/search";
	public String CREATE_DISCOVERY_PROFILE_INTERNAL="/tenants/{clientId}/discoveryProfiles";
	public String SEARCH_DISCOVERY_PROFILE_INTERNAL="/tenants/{tenantId}/discoveryProfiles/search";
	public String GET_DISCOVERY_PROFILE_INTERNAL="/tenants/{clientId}/discoveryProfiles/{discoveryId}";
	public String COMPLETE_DEVICE_SHEDULE_MAINTENANCE="/tenants/{clientId}/scheduleMaintenances/{smId}/complete";
	public String ADD_RESOURCES_TO_SCHEDULE_MAINTENANCE = "/tenants/{clientId}/scheduleMaintenances/{smId}/resources";
	public String GET_RESOURCES_ANTIVIRUSES_DETAILS="/tenants/{clientId}/resources/antivirus/search";
	public String GET_VIEW_BY_USERID = "/serviceProvider/users/{clientId}/serviceDesk/views/search";
	public String DELETE_INACTIVE_VIEW="/serviceProvider/users/{clientId}/serviceDesk/views/inactive?";
	public String GET_VIEW_BY_VIEW_ID = "/serviceProvider/users/{tenantId}/serviceDesk/views/{id}";
	public String CREATE_JOB_INTERNAL="/createJob";
	public String GET_JOBS_INTERNAL="/jobs/org/{orgId}";
	public String GET_JOB_INTERNAL="/jobs/{jobId}";
	public String RUN_JOB_INTERNAL="/jobs/{jobId}/action/run";
	public String ALERT_VIEW = "/tenants/{tenantId}/users/{id}/alertViews";
	public String ASSIGN_TEMPLATE_TO_RESOURCE="/tenants/{clientId}/resources/{resourceId}/templates";
	public String GET_ASSIGNED_TEMPLATES_OF_A_RESOURCE="/tenants/{clientId}/resources/{deviceId}/templates/search";
	public String SEARCH_TEMPLATE="/tenants/{tenantId}/monitoring/templates/search";
	public String GET_MONITORING_CONFIG_ON_RESOURCE="/tenants/{tenantId}/resources/{resourceId}/monitoringConfigurations";
	public String GET_FEEDBACK="/basic/feedback";
	public String GET_REVERSE_MAPPING = "/tenants/{clientId}/incidents/reverseMapping";
	public String GET_FORWARD_MAPPING = "/tenants/{clientId}/incidents/forwardMapping";
	public String ADD_LOCATION="/synthetics/locations";
	public String CREATE_SYNTHETIC="/tenants/{tenantId}/synthetics";
	public String DELETE_CHECK="/tenants/{tenantId}/synthetics/{id}";
	public String DELETE_LOCATION="/synthetics/locations/{uuid}";
	public String GET_ALL_CHECKS="/locations/{uuid}/checks";
	public String GET_COLLECTORS="/synthetics/locations/{uuid}/collectors";
	public String GET_LOCATION="/synthetics/locations/{uuid}";
	public String IS_CLOUD_READY="/checks/locations/{uuid}/isCloudReady";
	public String LOAD_CHECKS_INTO_CACHE="/synthetics/loadChecksIntoCache";
	public String MAP_WITH_LOCATION="/tenants/{tenantId}/locations/{id}/synthetics/sync";
	public String REGISTER_COLLECTOR="/checks/locations/{uuid}/collectors";
	public String SAVE_METRIC="/locations/{uuid}/checks/{checkId}/response";
	public String DELETE_INACTIVE_USER_VIEWS="/tenants/{tenantId}/users/{id}/serviceDesk/views/inactive";
	public String SEARCH_USERS="/tenants/{tenantId}/users/search";
	public String GET_VIEWS_BY_USERID="/tenants/{tenantId}/users/{id}/serviceDesk/views/search";
	public String GET_VIEWS_BY_VIEWID="/tenants/{tenantId}/users/{id}/serviceDesk/views/{viewId}";
	public String SAVE_TICKET_RESPONSE="/sdesk/tenants/{tenantId}/ticketResponse/save";
	public String SAVE_ACTIVITY_LOG="/sdesk/tenants/{tenantId}/activityLog/save";
	public String DELETE_ACTIVITY_LOG="/sdesk/tenants/{tenantId}/appId/{appId}/entityId/{entityId}/entityName/{entityName}/ts/{ts}/delete";
	public String GET_RESPONSE_BY_TICKETID="/sdesk/tenants/{tenantId}/ticketId/{ticketId}";
	public String GET_TICKET_RESPONSE_BY_TICKETID="/sdesk/tenants/{tenantId}/responseId/{ticketId}";
	public String GET_LATEST_RESPONSE="/sdesk/tenants/{tenantId}/ticketIds/{ticketId}/latestResponse";
	public String GET_FIRSTTICKET_RESPONSE="/sdesk/tenants/{tenantId}/ticketIds/{ticketId}/firstResponse";
	public String DELETE_TICKET_RESPONSE="/sdesk/tenants/{tenantId}/ticketIds/{ticketId}/responseId/{responseId}";
	public String GET_ACTIVITY_LOGS_BY_PAGINATION="/sdesk/tenants/{tenantId}/appId/{appId}/entityId/{entityId}/entityName/{entityName}";
	public String DISABLE_COMPONENT_METRICS_OF_RESOURCES="/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/components/{component}/metrics/{metric}/action/disable";
	public String ENABLE_COMPONENT_METRICS_OF_RESOURCES="/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/components/{component}/metrics/{metric}/action/enable";
	public String GET_AVAILABLE_METRICS_BY_METRICGROUP="/metric/tenants/{tenantId}/metricGroups/{metricGroup}";
	public String GET_DOWN_TIME_VALUES="/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/metrics/{mid}/downtimeValues?startTime={startTime}&endTime={endTime}";
	public String GET_METRICS_BY_METRICS="/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/metrics/{metric}";
	public String GET_METRICS_BY_RESOURCE_AND_METRIC_GROUPS="/metric/tenants/{tenantId}/resourceGroups/{resourceGroup}/metricGroups/{metricGroup}";
	public String GET_DATAPOINTS_BY_ROW_KEY="/metric/tenants/{tenantId}/rowKeys/{rowKey}/startDate/{startDate}/endDate/{endDate}";
	public String SAVE_DOWN_TIME_VALUES="/metric/tenants/{tenantId}/rtypes/{rtype}/resources/{resource}/downtime";
	public String PURGE_OLD_METRICS="/metric/tenants/{tenantId}/purgeOldMetrics?rtype={rtype}&resource={resource}";
	public String GET_RESOURCES_GROUPBY = "/tenants/{tenantId}/cloud/assets?queryString=";
	public String GET_CUSTOM_FIELDS="/tenants/{clientId}/customFields/{classCode}";
	public String GET_MIGRATE_SCHEDULE="/partners/migrateEscSchedules?mspId={tenantId}";
	public String ENABLE_POLICIES = "/partners/enableEscPolicies?mspId={tenantId}";
	public String ROLLBACK_POLICIES = "/partners/rollBackOldEscPolicies?mspId={tenantId}";
	public String SEARCH_PARTNER = "/tenants/search";	
	public String GET_MIGRATE_OLD_SCHEDULE ="/partners/migrateOldEscPolicies?mspId={tenantId}";
	public String GET_COST_BY_GROUPING="/tenants/{tenantId}/cloud/cost?queryString=";
	public String GET_CLOUD_BILL_COST="/tenants/{tenantId}/cloud/cloudBill/cost?queryString=";
	public String GET_SP_ATTRIBUTES_AND_VALUES="/serviceProvider/customAttributes/search";
	public String GET_SKU_INVENTORY="/tenants/{tenantId}/skus/inventory/search";
	public String CREATE_OR_UPDATE_FM="/serviceProvider/incidents/forwardMapping";
	public String CREATE_OR_UPDATE_RM="/serviceProvider/incidents/reverseMapping";
	public String CREATE_BUSINESS_IMPACT="/serviceProvider/incidents/businessImpacts";
	public String CREATE_URGENCY="/serviceProvider/incidents/urgencies";
	public String UPDATE_URGENCY="/serviceProvider/incidents/urgencies/{uniqueId}";
	public String GET_CHANGE_REQUESTS="/tenants/{clientId}/changeRequests/{changeRequestId}";
	public String PROBLEMS_CREATE_CATEGORY="/tenants/{clientId}/problems/categories";
	public String PROBLEMS_UPDATE_CATEGORY="/tenants/{clientId}/problems/categories/{problemId}";
	public String DELETE_RESOURCE_BY_TYPE="/tenants/{clientId}/resources/Resourcetype/{resourceType}/{resourceUUID}";
	public String GET_USERS_LOGIN_HISTORY="/tenants/{tenantId}/users/loginHistory/search";
	public String GET_DEVICE_WARRANTY="/tenants/{clientId}/devices/{deviceId}/deviceWarranty";
	public String GET_DEVICE_WARRANTIES="/tenants/{clientId}/deviceWarranties";
	public String CREATE_RBA_JOB="/tenants/{tenantId}/rba/jobs";
	public String DOWNLOAD_LINUX_AGENT="/tenants/{clientId}/agents/{platform}/{fileName}";
	public String GET_CHANGE_REQUEST_CUSTOM_FORM="/tenants/{clientId}/changeRequests/customForm";
	public String GET_INCIDENT_CUSTOM_FORM1="/tenants/{tenantId}/incidents/customForm";
	public String GET_PROBLEM_CUSTOM_FORM="/tenants/{clientId}/problems/customForm";
	public String GET_SERVICE_REQUEST_CUSTOM_FORM="/tenants/{clientId}/serviceRequests/customForm";
	public String GET_TASK_CUSTOM_FORM="/tenants/{clientId}/tasks/customForm";
	public String GET_TIME_BOUND_CUSTOM_FORM="/tenants/{clientId}/timeBoundRequests/customForm";
	public String CREATE_NOTE="/tenants/{clientId}/notes";
	public String DELETE_NOTE="/tenants/{tenantId}/notes/{id}";
	public String UPDATE_BUSINESS_IMPACT="/serviceProvider/incidents/businessImpacts/{uniqueId}";
	public String CADD_RESPONSE="/tenants/{tenantId}/changeRequests/{id}/responses";
	public String CLOSE_CHANGE_REQUEST="/tenants/{clientId}/changeRequests/{changeRequestId} /close";
	public String CGET_RESPONSES="/tenants/{clientId}/changeRequests/{changeRequestId}/responses/search";
	public String UPDATE_CHANGE_REQUEST="/tenants/{clientId}/changeRequests/{changeRequestId}";
	public String DOWNLOADABLE_LIST="/tenants/{tenantId}/reports/search";
	public String UPDATE_DISCOVERY_FILE="/tenants/{clientId}/discoveryProfiles/{discoveryID}";
	public String GET_DEVICE_APPLICATION="/tenants/{tenantId}/devices/applications";
	public String CREATE_CONSOLE="/tenants/{clientId}/devices/{deviceId}/remoteConsoles";
	public String CHANGE_WSUS_SETTING="/tenants/{tenantId}/devices/wsussettings/{id}";
	public String GET_GATEWAY_MONCONF_OUTOFSYNCDEVICES="/tenants/{tenantId}/gateway/monConfOutOfSyncDevices";
	public String SEARCH_SKUS="/serviceProvider/skus/search";
	public String RBA_CATEGORY="/serviceProvider/rba/categories";
	public String SR_CREATE_CATEGORY="/tenants/{clientId}/serviceRequests/categories";
	public String SR_UPDATE_CATEGORY="/tenants/{clientId}/serviceRequests/categories/{categoryId}";
	public String CREATE_TEMPLATE="/template/import";
	public String EXPORT_TEMPLATE="/template/export/{templateId}";
	public String SAMPLE_TEMPLATE="/template/sample";
	public String RUN_DEVICE_MANAGEMENT_POLICY="/tenants/{clientId}/policies/management/{deviceManagementPolicyId}/action/run";
	public String SEARCH_RBA_JOBS="/tenants/{tenantId}/rba/jobs/search";
	public String SEARCH_PROBLEMS="/tenants/{clientId}/problems/search";
	public String ICREATE_CATEGORY="/tenants/{clientId}/incidents/categories";
	public String IUPDATE_CATEGORY="/tenants/{clientId}/incidents/categories/{categoryId}";
	public String ICREATE_URGENCY="/tenants/{clientId}/incidents/urgencies";
	public String IUPDATE_URGENCY="/tenants/{clientId}/incidents/urgencies/{id}";
	public String GATEWAY_REGISTRATION="/gateway/activate";
	public String GET_GATEWAY_CONNECTION_NODE_DETAILS="/gateway/connectionNode/{gatewayUUID}";
	public String CREATE_PROFILE="/tenants/{clientId}/managementProfiles";
	public String SPCREATE_CATEGORY="/serviceProvider/serviceRequests/categories";
	public String SPUPDATE_CATEGORY="/serviceProvider/serviceRequests/categories/{uniqueId}";
	public String DELETE_RBA_JOB="/tenants/{tenantId}/rba/jobs/{id}";
	public String SPPROBLEMS_CREATE_CATEGORY="/serviceProvider/problems/categories";
	public String SPPROBLEMS_UPDATE_CATEGORY="/serviceProvider/problems/categories/{uniqueId}";
	public String GET_SP_USERS_LOGIN_HISTORY="/serviceProvider/users/loginHistory/search";
	public String DEVICE_CREATE_NOTE="/tenants/{clientId}/resources/{resourceId}/notes";
	public String DEVICE_SEARCH_NOTE="/tenants/{clientId}/resources/{resourceId}/notes/search";
	public String DEVICE_UPDATE_NOTE="/tenants/{clientId}/resources/{resourceId}/notes/{noteId}";
	public String SEARCH_TICKET_CONVERSATIONS="/tenants/{clientId}/{ticketType}/{ticketId}/conversations/search";
	public String GLOBAL_SEARCH_CLIENTS="/serviceProvider/clients/search";
	public String CR_CREATE_CATEGORY="/tenants/{clientId}/changeRequests/categories";
	public String CR_UPDATE_CATEGORY="/tenants/{clientId}/changeRequests/categories/{categoryId}";
	public String SP_ICREATE_CATEGORY="/serviceProvider/incidents/categories";
	public String SP_IUPDATE_CATEGORY="/serviceProvider/incidents/categories/{uniqueId}";
	public String CREATE_CREDENTIAL_SET="/tenants/{clientId}/credentialSets";
	public String DELETE_CREDENTIAL_SET="/tenants/{clientId}/credentialSets/{credentialSetId}";
	public String GET_CLIENT_MINIMAL_CREDENTIAL_SETS="/tenants/{clientId}/credentialSets/minimal";
	public String GET_DEVICE_MINIMAL_CREDENTIAL_SETS="/tenants/{clientId}/devices/{deviceId}/credentialSets/minimal";
	public String CREATE_GLOBAL_SCRIPT="/serviceProvider/rba/categories/{categoryId}/scripts";
	public String DELETE_GLOBAL_SCRIPT="/serviceProvider/rba/categories/{orgId}/scripts/{userId}";
	public String CREATE_ESCALATION_POLICY1="/tenants/{tenantId}/escalationPolicy";
	public String DOWNLOAD_LINUX_AGENT_INSTALLATION_SCRIPTS="/tenants/{clientId}/agents/deployAgentsScript";
	public String RUN_SCRIPT_JOB="/tenants/{clientId}/jobs/{id}/script/run";
	public String CREATE_SP_USER="/serviceProvider/users";
	public String GET_INVENTORY="/tenants/{tenantId}/resources/{id}/inventory/{valueID}";
	public String GET_SP_ROLES="/serviceProvider/roles/{roleId}";
	public String GET_POLICY_DEVICE_GRP="/tenants/{clientId}/policies/deviceGroups/{deviceGroupId}";
	public String ASSIGN_AGENT_PROFILE_ON_DEVICES="/tenants/{tenantId}/agentProfiles/{id}/devices";
	public String SEARCH_DEVICE="/tenants/{clientId}/devices/search";
	public String SEARCH_ESCALATION_POLICIES="/tenants/{tenantId}/escalationPolicies/search";
	public String CREATE_EMAIL_INCIDENT="/integrations/messages/incidents";
	public String UPDATE_INCIDENT_ID_FOR_ALETRT="/tenants/{clientId}/alerts/{alertId}/tickets/{ticketId}/update";
	public String CHECK_API="/checkAPI";
	public String PDOWNLOAD_RESPONSE_ATTACHEMENT="/tenants/{clientId}/problems/{problemId}/responses/{responseId}/resources/{resourceId}";
	public String CDOWNLOAD_RESPONSE_ATTACHEMENT="/tenants/{clientId}/{payloadType}/{id}/responses/{responseId}/resources/{resourceId}";
	public String DELETE_TICKETS="/sdesk/tickets/{method}";
	public String GET_INCIDENT_STATUS_CHANGE_REASONS="/tenants/{tenantId}/sdesk/statusReasons/INCIDENT";
	public String GET_THROTTING_LIMITS="/cfg/throttling";
	public String RELOAD_THROLITING_LIMITS="/cfg/throttling/reload";
	public String SAVE_SERVICEREQUEST_NO="/sdesk/servicerequestrepo/save";
	public String SAVE_ZIPCODEDETAILS="/sdesk/ziprepo/save";
	public String GET_ALL_SERVICEREQUESTNOS="/sdesk/servicerequestrepo/findall/";
	public String GET_ZIPCODEDETAILS_BY_ZIPCODE="/sdesk/ziprepo/zip/{zipcode}";
	public String GET_ZIPCODEDETAILS_BY_CITY="/sdesk/ziprepo/city/{city}";
	public String GET_SERVICEREQUESTNO_BY_CASEID="/sdesk/servicerequestrepo/get/{sr_id}";
	public String GET_SERVICEREQUESTNO_BY_PAGINATION="/sdesk/servicerequestrepo/get/{sr_id}/{pageNo}/{pageSize}";
	public String DELETE_SERVICEREQUESTNOS="/sdesk/servicerequestrepo/delete/id/{sr_ids}";
	public String DELETE_SERVICEREQUESTNO="/sdesk/servicerequestrepo/delete/id/{sr_id}";
	public String PERFORM_SLA_ACTION="/alerts/performSlaAction";
	public String CHANGE_STATUS="/metric/tenants/{clientId}/rtypes/{rtype}/resources/{resource}/mids/{mid}/changestatus";
	public String GET_TICKETRESPONSE_BY_TICKETID="/sdesk/tenants/{tenantId}/ticketId/{ticketId}";
	public String SAVE_DATALOG_THROUGH_SERVICELAYER="/metric/saveDataLog";
	public String GET_GATEWAY_RESOURCE_TOKEN ="/gateway/registration/{uuid}";
	public String CREATE_CUSTOM_REPORT = "/customReports/{tenantId}/";
	public String SEARCH_CUSTOM_REPORT = "/tenants/{tenantId}/customreports/search?pageNo={pageNo}&pageSize={pageSize}";
	public String GET_SCRIPT_DEMO="/tenants/{clientId}/scripts/{serviceName}/{deviceIp}/{deviceName}";
	public String MOVE_ALERT_TO_MONITORING="/alerts/tenants/{clientId}/moveAlertToMonitoring";
	public String GET_TICKET_RESPONSE_BY_TICKETIDS="/sdesk/tenants/{tenantId}/ticketIds/{ticketIds}/startTime/{startTime}/endTime/{endTime}";
	public String GET_IMLINK_ACTIVITY_LIST="/sdesk/appId/{appId}/tenants/{tenantId}?pageSize={pageSize}";
	public String METRIC_CHANGE_STATUS="/metric/changestatus";
	public String GET_DATA_LONGS="/metric/tenants/{tenantId}/metrics/api.token.success.stats/latestvalues";
	public String SAVE_ALETRT_STATE="/metric/alertState/save";
	public String GET_METRICSBY_TID_AND_MID="/metric/tenants/{tenantId}/metrics/{mid}/metrics";
	public String DELETE_DISABLE_METRICS="/{metric}/deleteDisabledMetrics";
	public String DELETE_RESOURCE="/tenants/{clientId}/resources/{resourceId}";
	public String GETNOTROLLEDUPTENANTS="/metric/getNotRolledUpTenants";
	public String GET_TIME_SERIES="/metric/query?tenant={tenantId}&resource={id}";
	public String GET_TICKET_RESPONSEBY_TID="/sdesk/tenants/{tenant}/ticketIds/{ticketIds}/startTime/{startTime}/endTime/{endTime}";
	public String GET_NC_BACKUP_FILE_DATA_OF_DEVICES="/tenants/{tenantId}/devices/{id}/ncbackup/confType/{valueID}";
	public String SAVE_NCONFIGURATION_BACKUP="/tenants/{tenantId}/resources/{id}/ncbbackup";
	public String UPDATE_EXT_ALT_STATE="/tenants/{tenantId}/alerts/heal?extAlertIds={id}";
	public String GET_TICKETEDALERT_COUNT="/alerts/count/alertsTicketed";
	public String CREATE_CUSTOM_REPORT_FOLDER = "/customreports/folder/create";
	public String GET_TICKETED_ALERTS_COUNT="/alerts/count/alertsTicketed";
	public String CHANGE_STATUS_LATEST_VALUE_BY_TIME="/metric/changestatus";
	public String GET_DATALOG_BY_RID_AND_MID="/metric/tenants/{tenantId}/metrics/api.token.success.stats/latestvalues";
	public String SAVE_ALERT_STATE="/metric/alertState/save";
	public String GET_METRICS_BY_TID_MID="/metric/tenants/{tenantId}/metrics/{mid}/metrics";
	public String GET_NOT_ROLLED_UP_TENANTS="/metric/getNotRolledUpTenants";
	public String GET_NC_BACKUPFILE_DATA_OF_DEVICE="/tenants/{clientId}/devices/{deviceId}/ncbackup/confType/{confType}";
	public String SAVE_NC_CONFIG_BACKUP="/tenants/{clientId}/resources/{resourceId}/ncbbackup";
	public String GET_ADDRESS_BY_ZIPCODE="/{zipcode}/addressDetails";
	public String VALIDATE_ACCOUNT_NUMBER="/checkIfPartnerAccNoExists/{id}/{accNo}";
	public String VALIDATE_PARTNER_NAME="/checkIfPartnerExists/{id}/{name}";
	public String CREATE_PARTNER_FROM_IMLINK_REGISTRATION="/partner/registration";
	public String GET_WORKFLOW_LOG_BY_TICKETID = "/sdesk/tenants/{tenant}/ticketId/{ticketId}/resClkStatus/{resClkStatus}/ts/{ts}/workflowLog";
	public String UPDATE_WORKFLOW_LOG="/sdesk/tenants/{tenantId}/workflowLog/update/approvalState";
	public String UPDATE_WORKFLOW_LOG_NOTES="/sdesk/tenants/{tenantId}/workflowLog/update/notes";
	public String GET_WORKFLOW_LOG_TICKETID="/sdesk/tenants/{tenantId}/ticketId/{ticketId}/workflowLog";
	public String UPDATE_WORKFLOW_LOG_TIMESPENT="/sdesk/tenants/{tenantId}/workflowLog/update/timeSpent";
	public String SAVE_WORKFLOW_LOG="/sdesk//tenants/{tenantId}/workflowLog/save";
	public String RESET_INTEGRATION_MAPPINGS="/tenants/{clientId}/integrations/installed/{installedIntgId}/mappingAttr/reset";
	public String UPDATE_INTEGRATION_FAIL_NOTIFIER="/tenants/{tenantId}/integrations/installed/{roleId}/failureNotifier";
	public String AUDIT_REPACTIVITY="/audit/repactivity/query";
	public String AUDIT_REPACTIVITY_LOG="/audit/repactivitylog/query";
	public String GET_AUDIT_ACTIVITY_REPORT="/audit/report/activity/query";
	public String DELETE_AUDIT_REPACTIVITYLOG="/audit/repactivitylog/delete";
	public String DELETE_AUDIT_REPACTIVITY="/audit/repactivity/delete";
	public String HISTORY_COUNT_RESOURCES="/history/tenant/{tenantId}/resources/count";
	public String HISTORY_GET_RESOURCES="/history/resource";
	public String HISTORY_GET_RESOURCE="/history/resource/{id}";
	public String HISTORY_SEARCH_RESOURCES="/history/tenant/{tenantId}/resources/search";
	public String HISTORY_REINDEX_ALLRESOURCES="/history/reindex/allresource";
	public String SEARCH_REPORTS="/tenants/{clientId}/{ticketType}/reports/search";
	public String UPDATE_ALL_REACTIVITY="/audit/repactivity/updateAll/";
	public String AUDIT_CREATE_REPACTIVITY="/audit/repactivity";
	public String AUDIT_CREATE_REPACTIVITYLOG="/audit/repactivitylog";
	public String AUDIT_UPDATE_REPACTIVITYLOG="/audit/repactivitylog/updateAll";
	public String HISTORY_CREATE_RESOURCE="/history/resource";
	public String HISTORY_CREATE_UPDATEPROVIDER="/history/updateProvider";
	public String GET_POLICY_ACTIVITY="/audit/policyActivity/query";
	public String GET_POLICY_ACTIVITY_COUNT="/audit/policyActivity/count";
	public String SAVE_POLICY_ACTIVITY_LOG="/audit/policyActivity";
	public String GET_RESOURCES_STATUS="/tenants/{clientId}/resources/{resourceId}/availability/status";
	public String METRIC_DATA_LOG_SAVE="/metric/dataLogs/save";
	public String SEARCH_RESOURCE_USING_EXTERNALUUID="/cloud/cloudProvider/{cloudProviderUniqueId}/resource?resourceId={resourceExternalUUID}";
	public String LAST_CONNCECTED_INFO="/cloud/cloudProvider/{cloudProviderUniqueId}/lastCollectedInfo";
	public String DELETE_CUSTOM_REPORT="/tenants/{tenantId}/customreports/delete/id/{id}";
	public String SAVE_RCA = "/checks/locations/{uuid}/rca";
	public String FOLDER_SEARCH_CUSTOM_REPORT="/customreports/folder/search";
	public String GET_DEVICE_VOL_DETAILS="/tenants/{clientId}/resources/{resourceId}/inventory/disks";
	public String SELF_SIGN="/selfsign/register";
	public String GET_RECENT_PATCH_FAILURE="/tenants/{clientId}/resources/patches/failures";
	public String GET_RESOURCE_PATCHES="/tenants/{clientId}/resources/patches";
	public String GET_RESOURCCE_PATCHES_SUMMARY="/tenants/{clientId}/resources/{resourceId}/patches/summary";
	public String DELETE_FOLDER_CUSTOM_REPORT="/customreports/folder/delete/id/{id}";
	public String GET_RESOURCE_PATCH_SUMMARY_BY_PARAM="/tenants/{clientId}/resources/patches/{resourceId}/summary";
	public String GET_PATCH_SUMMARY_BY_QUERY="/tenants/{tenantId}/resources/patches/COUNTS/summary?queryString{queryString}";
	public String GET_TOPOLOGY_BY_RESOURCE_ID="/tenants/{clientId}/resources/{resourceId}/topology";
	public String GET_TOPOLOGY_BY_IP="/tenants/{clientId}/topology?ipAddress={IP}&searchType=IN&depth=30";
	public String GET_VERTICES_BY_EDGE_PROPERTY="/tenants/{clientId}/edgevertices?edgeProperty=tgtInt:FastEthernet0";
	public String DELETE_TOPOLOGY_BY_VERTES_PROPERTY="/tenants/{clientId}/deleteTopology?profileId=1";
	public String GET_LIST_OF_UNMANAGED_DEVICE="/tenants/{clientId}/topology/unmanagedDevices";
	public String GET_LIST_OF_VLAN_AVAILABLE_DEVICE="/tenants/{clientId}/topology/availableVLAN?";
	public String GET_NEIGBOURS_OF_DEVICE= "/tenants/{clientId}/topology/neighbours?";
	public String GET_TOPOLOGY_BY_IPADDRESS="/tenants/{clientId}/topology/topologyInfo?ipAddress={IP}&depth=4";
	
	
	public String GET_FORECAST="/tenants/{clientId}/timeseries/forecast/{type}/{resourceId}/{metricName}/search?startTime={startTime}&endTime={endTime}";
	public String GET_ENABLED_FORECAST="/tenants/{clientId}/timeseries/forecast";
	public String GET_ENABLED_CHANGE_DETECTION="/tenants/{clientId}/timeseries/changeDetection";
	public String GET_DETECTED_CHANGE="/tenants/{clientId}/timeseries/changeDetection/{type}/{resourceId}";
	public String ENABLED_FORECAST="/tenants/{clientId}/timeseries/forecast/{type}/{resourceId}/{metricName}?startTime={startTime}&forecastTimeStep={endTime}";
	public String ENBALE_CHANGE_DETECTION="/tenants/{clientId}/timeseries/changeDetection/{type}/{resourceId}/{metricName}?confidenceLevel={confidenceLevel}";
	public String DISABLE_CHANGE_DETECTION="/tenants/{clientId}/timeseries/changeDetection/{type}/{resourceId}";
	public String GET_METRIC_LEGEND="/metricstore/metricsLegend/netapp.filer.disk.raid-state";
	
	public String CREATE_NEW_SERVICE_GROUP="/tenants/{clientId}/serviceGroups";
	public String GET_ROOT_SERVICE_GROUPS="/tenants/{clientId}/serviceGroups/search?pageSize={pageSize}";
	public String GET_NEW_SERVICE_GROUP="/tenants/{tenantId}/serviceGroups/{id}";
	public String GET_SERVICE_GROUP_CHILDS="/tenants/{tenantId}/serviceGroups/{id}/childs/search";
	public String ASSIGN_CHILDS_NEW_SERVICE_GROUP="/tenants/{tenantId}/serviceGroups/{id}/childs";
	
	public String PATCH_FEED_SEARCH_PATCHES="/tenants/{clientId}/patches";
	public String GET_PATCH_FEED="/tenants/{clientId}/patches/rating/{intgId}/feed/{patchId}";
	public String CREATE_PATCH_FEED="/tenants/{clientId}/patches/rating/{intgId}/feed";
	public String DELETE_PATCH_FEED="/tenants/{clientId}/patches/rating/{intgId}/feed/{patchId}";
	
	public String DATA_RETENSION_MODULE ="/solutionProvider/partners/{mspId}/{module}/{action}";
	public String DECOMISSION_RESOURCE="/tenants/{clientId}/resources/{resourceId}/decommission";
	public String GET_HISTORY_RESOURCES="/tenants/{clientId}/history/resources/{resourceId}";
	public String SEARCH_HISTORY_RESOURCES="/tenants/{clientId}/history/resources";
	
	public String CREATE_RESOURCE="/tenants/{clientId}/resources";
	public String GET_MINIMAL_RESOURCES_TYPES = "/tenants/{clientId}/resourceType/minimal";
	public String GET_MINIMAL_RESOURCES = "/tenants/{clientId}/resources/minimal/";
	public String GET_RESOURCES_APPLICATIONS="/tenants/{clientId}/resources/{resourceId}/applications";
	public String GET_RESOURCES_AVAILABILITY = "/tenants/{clientId}/resources/ResourceType/{resourceType}/{resourceUUID}/availability";
	public String UPDATE_RESOURCE= "/tenants/{clientId}/resources/{resourceId}";
	public String GET_AVAILABILITY_RULE="/tenants/{clientId}/resources/{resourceId}/availabilityRule";
	public String ALERT_NOTIFICATION_PREFERENCE="/tenants/{tenantId}/users/NotifyMethod";
	public String SAVE_DATA_LOG_NEW_TABLE = "/metric/saveDataLogInNewTables?clientid=";
	public String GET_UNMANAGED_RESOURCE="/tenants/{tenantId}&metric=system.ping.rta&startTime={startTime}&endTime={endTime}&byRtype";
	public String GET_MANAGED_RESOURCE_COUNT = "/tenants/{tenantId}&metric=system.ping.rta&startTime={startTime}&endTime={endTime}&byRtype";
	public String GET_DISCOVERED_RESOURCE_COUNT="/tenants/{tenantId}&metric=system.ping.rta&startTime={startTime}&endTime={endTime}&byRtype";
	public String GET_CLOUD_RESOURCES="/tenants/{tenantId}/cloud/assets?queryString=groupBy:tag+sourceType:DEVICE";
	public String GET_CLOUD_PROVIDER_ACTIVITY_BY_TIME="/audit/cloudProviderActivity/{cloudProviderId}/query?cptype=AWS";
	public String GET_lATEST_CLOUD_ACTIVITY="/audit/cloudProviderActivity/{cloudProviderId}/latest";
	public String SAVE_CLOUDE_PROVIDER_ACTIVITY="/audit/cloudProviderActivity";
	public String DOWNLOAD_KBN_CONFIG_FILES="/tenants/{clientId}/integrations/installed/{installedIntgId}/configFile/{fileName}";
	public String GET_OOB_INTERFACE_CARDS="/tenants/{clientId}/resources/{resourceId}/inventory/oobInterfaceCards";
	
	public String GET_AVAILABILITY_EVENTS="/tenants/{clientId}/resources/{resourceId}/availability/events?metricNames= {mn}";
	public String GET_RESOURCE_AVAILABILITY_REASON="/tenants/{clientId}/resources/{resourceId}/availability/reason";
	public String SAVE_AVAILABILITY_EVENTS="/tenants/{clientId}/resources/{resourceId}/availability/events";
	public String SAVE_ENTITY_OUTAGE_BY_ROW_KEY="/metric/key/{resourceId}/outage";
	public String SAVE_RESOURCE_DOWN_TIME="/tenants/{clientId}/resources/{resourceId}/availability/downtime";
	public String SAVE_RESOURCE_OUTAGE="/tenants/{clientId}/resources/{resourceId}/availability/outage";
	public String GET_SERVICE_AVAILABILITY_REASON="/tenants/{clientId}/services/{resourceId}/availability/reason";
	public String GET_SERVICE_AVAILABILITY_STATUS="/tenants/{clientId}/services/{resourceId}/availability/status";
	public String SAVE_SERVICE_DOWNTIME="/tenants/{clientId}/services/{resourceId}/availability/downtime";
	public String SAVE_SERVICE_OUTAGE="/tenants/{clientId}/services/{resourceId}/availability/outage";
	public String GET_SERVICE_AVAILABILITY="/tenants/{tenantId}/services/{id}/availability";
	public String GET_RESOURCE_AVAILABILITY = "/tenants/{clientId}/resources/{resourceId}/availability";
	public String UPDATE_AVAILABILITY_RULE="/tenants/{clientId}/resources/{resourceId}/availability/rule";
	public String LINK_SERVICE_GROUP = "/tenants/{clientId}/serviceGroups/link";
	public String UNLINK_SERVICE_GROUP= "/tenants/{clientId}/serviceGroups/unLink/{parentSgId}/{childSgId}";
	
	public String CREATE_ASSOCIATIONS="/tenants/{tenantId}/metadata/associations";
	public String GET_ALERTS_DATA="/alerts/altIDs/{id}";
	public String GET_ESCALATE_ALERTS_NOTIFICATIONS="/audit/escAlertsActivity/query";
	public String GET_ESCALATE_ALERTS_NOTIFICATIONS_COUNT="/audit/escAlertsActivity/count";
	public String SAVE_ESCALATE_ALERTS_NOTIFICATIONS="/audit/escAlertsActivity";
	public String GET_PATCH_BASELINES="/tenants/{clientId}/patches/baselines";
	public String GET_PATCHES="/tenants/{clientId}/patches/baselines/{baseLineId}";
	public String GET_COMPLIANCE="/tenants/{tenantId}/resources/{resourceId}/baselines/{id}/patches";
	
	public String CREATE_FORMS="/tenants/{tenantId}/metadata/forms";
	public String GET_ClOUD_WATCH_METRICS_COUNT ="/cloud/cloudProvider/{cloudProviderUniqueId}/metrics?serviceTypeMetrics=false";
	public String GET_CLOUD_COST="/tenants/{tenantId}/cloud/cloudBill/cost?queryString=";
	public String GET_CUSTOM_ATTRIBUTE_RESOURCES = "/tenants/{clientId}/customAttributes/resources";
	public String GET_ACTIVITY_LOG="/tenants/{clientId}/{entityName}/{entityId}/activitylog";
	public String GET_LATEST_METRIC_VALUES = "/metric/tenants/{clientId}/metrics/{metricName}/latestvalues";
	public String DELETE_FILE = "/tenants/{clientId}/machineLearning/files/{fileId}";
	public String SESRCH_FILES = "/tenants/{clientId}/machineLearning/files";
	public String ANALYZE_DATA = "/tenants/{clientId}/commands";
	
	public String GET_METRIC_LAST_COLLECTED_TIME = "/metric/tenants/{tenantId}/metrics/resource/{resourceUUID}/lastCollectedTime";
	public String GET_LAST_SCANNED_TIME = "/tenants/{tenantId}/integration/{installedIntgId}/scan/lastScannedTime";
	public String GET_USERS_OF_USERGROUP = "/tenants/{tenantId}/userGroups/{userGroupId}/users";
	public String REMOVE_USERS_FROM_USERGROUP = "/tenants/{tenantId}/userGroups/{userGroupId}/users";
	public String SEARCH_USERGROUPS = "/tenants/{tenantId}/userGroups";
	public String UPDATE_USERGROUP = "/tenants/{tenantId}/userGroups/{userGroupId}";
	public String GET_ROLE = "/tenants/{tenantId}/roles/{roleId}";
	public String UPDATE_ROLE = "/tenants/{tenantId}/roles/{roleId}";
	public String GET_NOTE = "/tenants/{clientId}/notes/{noteId}";
	public String SEARCH_NOTES = "/tenants/{clientId}/notes";
	public String UPDATE_NOTE = "/tenants/{clientId}/notes/{id}";
	public String GET_MINIMAL_DEVICES = "/tenants/{clientId}/devices/minimal";
	public String GET_CREDENTIAL_SET = "/tenants/{clientId}/credentialSets/{credentialSetId}";
	public String GET_CREDENTIAL_SETS = "/tenants/{clientId}/credentialSets";
	public String UPDATE_CREDENTIAL_SET = "/tenants/{clientId}/credentialSets/{credentialSetId}";
	public String GET_CIRCUITCARDS = "/tenants/{clientId}/resources/{resourceId}/inventory/pbxCircuitCards";
	public String GET_LICENSE = "/tenants/{clientId}/resources/{resourceId}/inventory/pbxLicense";
	public String GET_PORTS = "/tenants/{clientId}/resources/{resourceId}/inventory/pbxPorts";
	public String GET_REGISTRATIONS = "/tenants/{clientId}/resources/{resourceId}/inventory/pbxRegistrations";
	public String GET_TRUNKS = "/tenants/{clientId}/resources/{resourceId}/inventory/pbxTrunks";
	public String GET_DISKDRIVES = "/tenants/{clientId}/resources/{resourceId}/inventory/disks";
	public String GET_MANAGEMENT_PROFILE = "/tenants/{clientId}/managementProfiles/{id}";
	public String UPDATE_MANAGEMENT_PROFILE = "/tenants/{clientId}/managementProfiles/{id}";
	public String UPDATE_SERVICE_REQUEST = "/tenants/{clientId}/serviceRequests/{serviceRequestId}";
	public String UPDATE_INCIDENT = "/tenants/{clientId}/incidents/{incidentId}";
	public String ADD_RESPONSE_TO_CHANGEREQUEST = "/tenants/{clientId}/changeRequests/{changeRequestId}/responses";
	public String GET_MANAGEMENT_POLICIES = "/tenants/{clientId}/policies/management";
	public String GET_MANAGEMENT_POLICY = "/tenants/{clientId}/policies/management/{deviceManagementPolicyId}";
	public String UPDATE_MANAGEMENT_POLICY = "/tenants/{clientId}/policies/management/{deviceManagementPolicyId}";
	public String GET_CONSOLES = "/tenants/{clientId}/devices/{deviceId}/remoteConsoles";
	public String CREATE_DEVICE_WARRANTY = "/tenants/{clientId}/devices/{deviceId}/deviceWarranty";
	public String DELETE_SITE = "/tenants/{clientId}/sites/{siteId}";
	public String UPDATE_SITE = "/tenants/{clientId}/sites/{siteId}";
	public String UPDATE_PROBLEM="/tenants/{clientId}/problems/{problemId}";
	public String GET_TASK = "/tenants/{clientId}/tasks/{taskId}";
	public String UPDATE_TIMEBOUNDREQUEST = "/tenants/{clientId}/timeBoundRequests/{timeBoundRequestId}";
	public String GET_SERVICEDESK_NOTES = "/tenants/{clientId}/{ticketType}/{ticketId}/notes/{noteId}";
	public String GET_SERVICEDESK_NOTES_LIST = "/tenants/{clientId}/{ticketType}/{ticketId}/notes";
	public String UPDATE_SERVICEDESK_NOTES = "/tenants/{clientId}/{ticketType}/{ticketId}/notes/{noteId}";
	public String CREATE_INCIDENT_BUSINESS_IMPACT = "/tenants/{clientId}/incidents/businessImpacts";
	public String UPDATE_INCIDENT_BUSINESS_IMPACT = "/tenants/{clientId}/incidents/businessImpacts/{uniqueId}";
	public String CREATE_OR_UPDATE_INCIDENT_FORWARD_MAPPING = "/tenants/{clientId}/incidents/forwardMapping";
	public String CREATE_OR_UPDATE_INCIDENT_REVERSE_MAPPING = "/tenants/{clientId}/incidents/reverseMapping";
	public String CREATE_SERVICE_DESK_STATUS_CHANGE_REASON = "/tenants/{clientId}/statusChangeReasons";
	public String GET_SERVICE_DESK_STATUS_CHANGE_REASON = "/tenants/{clientId}/statusChangeReasons/{reasonId}";
	public String UPDATE_SERVICE_DESK_STATUS_CHANGE_REASON = "/tenants/{clientId}/statusChangeReasons/{reasonId}";
	public String GET_SERVICE_DESK_STATUS_CHANGE_REASONS_BY_CLIENT = "/tenants/{clientId}/statusChangeReasons";
	public String KB_CATEGORY_LIST="/tenants/{clientId}/kb/categorylist";
	public String DELETE_KB_CATEGORY="/tenants/{clientId}/kb/category/delete/{categoryId}";
	public String UPDATE_KB_CATEGORY="/tenants/{clientId}/kb/category/update/{categoryId}";
	public String GET_KB_CATEGORY="/tenants/{clientId}/kb/category/{categoryId}" ;
	public String CREATE_KB_CATEGORY="/tenants/{clientId}/kb/category/create";
	public String KB_SUBCATEGORY_LIST="/tenants/{clientId}/kb/categorylist/{categoryId}";
	public String CREATE_PATCH_BASELINE = "/tenants/{clientId}/patches/baselines";
	public String UPDATE_PATCH_BASELINE = "/tenants/{clientId}/patches/baselines/{baseLineId}";
	public String ASSIGN_UNASSIGN_BASELINE_PATCH = "/tenants/{clientId}/patches/baselines/{baseLineId}/{patchId}/{action}";
	public String ACTIVATE_DEACTIVATE_BASELINE = "/tenants/{clientId}/patches/baselines/{baseLineId}/{action}";
	public String DELETE_BASELINE = "/tenants/{clientId}/patches/baselines/{baseLineId}";
	
	public String CREATE_KB_ARTICLE="/tenants/{clientId}/kb/article";
	public String GET_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}";
	public String ADD_COMMENT_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}/comment";
	public String GET_KB_ARTICLE_ACTIVITYLOG="/tenants/{clientId}/kb/article/{articleId}/activityLog";
	public String GET_KB_ARTICLES_BYCATEGORY="/tenants/{clientId}/kb/articlesList";
	public String KB_GET_ATTACHMENTS_BYARTICLE="/tenants/{clientId}/kb/article/{articleId}/resources/{resourceId}";
	public String GET_COMMENTSLIST_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}/comments";
	public String GET_ATTACHMENTS_BYCOMMENT_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}/comments/{commentId}/resources/{resourceId}";
	public String SHARE_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}/share";
	public String UPDATE_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}";
	public String SEARCH_KB_ARTICLES="/tenants/{clientId}/kb/articles/search";
	public String DELETE_KB_ARTICLE="/tenants/{clientId}/kb/article/{articleId}/delete";
	
	public String CREATE_NOTIFICATION_TEMPLATE="/tenants/{clientId}/notifications/templates";
	public String GET_NOTIFICATION_TEMPLATE="/tenants/{clientId}/notifications/templates/{templateId}";
	public String UPDATE_NOTIFICATION_TEMPLATE="/tenants/{clientId}/notifications/templates/{templateId}";
	public String DELETE_NOTIFICATION_TEMPLATE="/tenants/{clientId}/notifications/templates/{templateId}";
	
	public String CREATE_ON_DEMAND_DATA_EXPORT_TEMPLATE = "/exports/tenants/{tenantId}/create";
	public String CREATE_DAILY_RECURRING_DATA_EXPORT_TEMPLATE = "/exports/tenants/{tenantId}/create";
	public String CREATE_MONTHLY_RECURRING_DATA_EXPORT_TEMPLATE = "/exports/tenants/{tenantId}/create";
	public String CREATE_WEEKLY_RECURRING_DATA_EXPORT_TEMPLATE = "/exports/tenants/{tenantId}/create";
	
	public String RESTORE_KB_CATEGORY="/tenants/{clientId}/kb/category/restore/{categoryId}";
	public String CREATE_COMPLIANCE = "/tenants/{clientId}/patches/compliance";
	public String DELETE_COMPLIANCE = "/tenants/{clientId}/patches/compliance/{complianceId}";
	public String RUN_COMPLIANCE = "/tenants/{clientId}/patches/compliance/{complianceId}/run";
	public String GET_ALL_COMPLIANCES_BY_CLIENT = "/tenants/{clientId}/patches/compliance";
	public String UPDATE_COMPLIANCE = "/tenants/{clientId}/patches/compliance/{complianceId}";
	public String GET_COMPLIANCE_OF_RESOURCE_AND_BASELINE = "/tenants/{clientId}/resources/{resourceId}/baselines/{baseLineId}/patches";
	public String GET_BASELINE_DETAILS_OF_COMPLINACE = "/tenants/{clientId}/patches/compliance/{complianceId}/baselines";
	public String GET_DEVICE_GROUPS_DETAILS_OF_COMPLIANCE = "/tenants/{clientId}/patches/compliance/{complianceId}/deviceGroups";
	public String GET_DEVICES_DETAILS_OF_COMPLINACE = "/tenants/{clientId}/patches/compliance/{complianceId}/devices";
	public String ASSIGN_UNASSIGN_BASELINE = "/tenants/{clientId}/patches/compliance/{complianceId}/baselines/{baseLineId}/{action}";
	public String ASSIGN_UNASSIGN_DEVICE = "/tenants/{clientId}/patches/compliance/{complianceId}/devices/{deviceId}/{action}";
	public String ASSIGN_UNASSIGN_DEVICEGROUP = "/tenants/{clientId}/patches/compliance/{complianceId}/deviceGroups/{deviceGroupId}/{action}";
	public String APPROVE_UNAPPROVE_PATCH = "/tenants/{clientId}/resources/{resourceId}/patches/{patchId}/{approvalType}";
	public String GET_PATCHING_STATUS_OF_RESOURCE = "/tenants/{clientId}/resources/{resourceId}/patches/install/status";
	public String GET_PATCH_STATUS_OF_RESOURCE ="/tenants/{clientId}/resources/{resourceId}/patches/scan/status";
	public String GET_PATCH_SCAN_STATUS_OF_ALL_DEVICES_IN_MISSING_JOB = "/tenants/{clientId}/patches/{jobId}/scan/status";
	public String GET_PATCHING_STATUS_OF_ALL_DEVICES_IN_PATCH_CONFIG = "/tenants/{clientId}/patches/{jobId}/install/status";
	public String CREATE_JOB = "/tenants/{clientId}/jobs";
	public String UPDATE_JOB = "/tenants/{clientId}/jobs/{id}";
	public String UNASIGN_DEVICES_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/{id}/devices";
	public String ASIGN_DEVICES_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/{id}/devices";
	public String ASSIGN_DEVICES = "/tenants/{clientId}/jobs/{id}/devices";
	public String UPDATE_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/{id}";
	public String DELETE_JOB = "/tenants/{clientId}/jobs/{id}";
	public String DELETE_PATCH_CONFIG = "/tenants/{clientId}/patches/configurations/{id}";
	public String CREATE_KB_TEMPLATE = "/tenants/{clientId}/kb/template";
	public String DELETE_KB_TEMPLATE = "/tenants/{clientId}/kb/template/{templateId}/delete";
	public String GET_KB_TEMPLATE = "/tenants/{clientId}/kb/template/{templateId}";
	public String GET_KB_TEMPLATES_LIST_BY_CATEGORY = "/tenants/{clientId}/kb/templatesList?categoryId={categoryId}";
	public String UPDATE_KB_TEMPLATE = "/tenants/{clientId}/kb/template/{templateId}";
	public String SEARCH_AVAILABLE_INTEGRATIONS = "/tenants/{clientId}/integrations/available/search";
	public String UPDATE_INTEGRATION_EVENT = "/tenants/{clientId}/integrations/installed/{installedIntgId}/event/{eventId}";
	public String ACTIVATE_INTEGRATION_EVENT = "/tenants/{clientId}/integrations/installed/{installedIntgId}/event/{eventId}/activate";
	public String GET_INTEGRATION_EVENT_PALCE_HOLDERS = "/tenants/{clientId}/integrations/events/placeHolders/{entityType}";
	public String CREATE_OR_UPDATE_INBOUND_AUTHENTICATION = "/tenants/{clientId}/integrations/installed/{installedIntgId}/inbound/authentication";
	public String CREATE_OR_UPDATE_INSTALLED_INTEGRATION_MAPPING = "/tenants/{clientId}/integrations/installed/{installedIntgId}/mappingAttr";
	public String CREATE_OR_UPDATE_INSTALLED_INTEGRATION_BASENOTIFIER = "/tenants/{clientId}/integrations/installed/{installedIntgId}/notifier";
	public String CREATE_OR_UPDATE_INTEGRATION_FAILURE_NOTIFIER = "/tenants/{clientId}/integrations/installed/{installedIntgId}/failureNotifier";
	public String DISABLE_INSTALLED_INTEGRATION = "/tenants/{clientId}/integrations/installed/{installedIntgId}/disable";
	public String ENABLE_INSTALLED_INTEGRATION = "/tenants/{clientId}/integrations/installed/{installedIntgId}/enable";
	public String DOWNLOAD_RESPONSE_ATTACHMENT_FROM_SERVICEREQUEST = "/tenants/{clientId}/serviceRequests/{serviceRequestId}/responses/{responseId}/resources/{resourceId}";
	public String ATTACH_GATEWAY_TO_PROFILE="/tenants/{clientId}/managementProfiles/{id}/attach";
	public String DETACH_GATEWAY_FROM_PROFILE="/tenants/{clientId}/managementProfiles/{id}/detach"; 
	public String RECONNECT_TUNNEL="/tenants/{clientId}/managementProfiles/{id}/reconnectTunnel";
	public String CREATE_IMPACT_DEPENDENCY="/tenants/{clientId}/dependencies/{resourceuuid}";
	public String GET_IMPACT_DEPENDENCY="/tenants/{clientId}/dependencies/{resourceuuid}";
	public String DELETE_IMPACT_DEPENDENCY="/tenants/{clientId}/dependencies/{resourceuuid}";
	public String CREATE_ROSTER = "/tenants/{clientId}/rosters";
	public String DELETE_ROSTER = "/tenants/{clientId}/rosters/{id}";
	public String SEARCH_ROSTER = "/tenants/{clientId}/rosters/search";
	public String GET_ROSTER="/tenants/{clientId}/rosters/{id}";
	public String UPDATE_ROSTER="/tenants/{clientId}/rosters/{id}";
	public String INSTALL_EMAIL_INTEGRATION = "/tenants/{clientId}/integrations/install/Email Alerts";
	public String SEARCH_MONITORABLE_RESOURCES = "/tenants/{clientId}/integrations/installed/{installedIntgId}/resources/monitorable/search";
	
	public String CREATE_SP_ATTRIBUTE_TYPE_AND_VALUES="/serviceProvider/customAttributes";
	public String CREATE_CUSTOM_ATTRIBUTE_PARTNER = "/tenants/{mspId}/customAttributes";
	public String CREATE_CUSTOM_ATTRIBUTE_CLIENT = "/tenants/{clientId}/customAttributes";
	public String UPDATE_SP_CUSTOM_ATTRIBUTE="/serviceProvider/customAttributes/{spAttributeId}";
	public String UPDATE_CLIENT_CUSTOM_ATTRIBUTE="/tenants/{clientId}/customAttributes/{clientAttributeId}";
	public String UPDATE_PARTNER_CUSTOM_ATTRIBUTE="/tenants/{mspId}/customAttributes/{partnerAttributeId}";
	public String GET_SP_CUSTOM_ATTRIBUTE_WITH_VALUE="/serviceProvider/customAttributes/{spAttributeId}";
	public String GET_CLIENT_CUSTOM_ATTRIBUTE_VALUE="/tenants/{clientId}/customAttributes/{clientAttributeId}";
	public String GET_PARTNER_CUSTOM_ATTRIBUTE_VALUE="/tenants/{mspId}/customAttributes/{partnerAttributeId}";
	public String SEARCH_SP_CUSTOM_ATTRIBUTES="/serviceProvider/customAttributes/search";
	public String SEARCH_CLIENT_CUSTOM_ATTRIBUTES="/tenants/{clientId}/customAttributes/search";
	public String SEARCH_PARTNER_CUSTOM_ATTRIBUTES="/tenants/{mspId}/customAttributes/search";
	public String DELETE_SP_CUSTOM_ATTRIBUTE="/serviceProvider/customAttributes/{spAttributeId}";
	public String DELETE_CLIENT_CUSTOM_ATTRIBUTE="/tenants/{clientId}/customAttributes/{clientAttributeId}";
	public String DELETE_PARTNER_CUSTOM_ATTRIBUTE="/tenants/{mspId}/customAttributes/{partnerAttributeId}";
	public String UPDATE_SP_CUSTOM_ATTRIBUTE_VALUE="/serviceProvider/customAttributes/{spAttributeId}/values/{spAttributeValueId}";
	public String UPDATE_CLIENT_CUSTOM_ATTRIBUTE_VALUE="/tenants/{clientId}/customAttributes/{clientAttributeId}/values/{clientAttributeValueId}";
	public String UPDATE_PARTNER_CUSTOM_ATTRIBUTE_VALUE="/tenants/{mspId}/customAttributes/{partnerAttributeId}/values/{partnerAttributeValueId}";
	public String ASSIGN_PARTNER_TO_CUSTOM_ATTRIBUTE="/serviceProvider/customAttributes/{spAttributeId}/values/{spAttributeValueId}/partners";
	public String ASSIGN_CLIENT_TO_CUSTOM_ATTRIBUTE="/tenants/{mspId}/customAttributes/{partnerAttributeId}/values/{partnerAttributeValueId}/clients";
	public String ASSIGN_DEVICES_TO_CUSTOM_ATTRIBUTE="/tenants/{clientId}/customAttributes/{clientAttributeId}/values/{clientAttributeValueId}/devices";	
	public String GET_ASSIGNED_ENTITIES_BY_ATTRIBUTE_SP="/serviceProvider/customAttributes/{spAttributeId}/assignedEntities/search";
	public String GET_ASSIGNED_ENTITIES_BY_ATTRIBUTE_PARTNER="/tenants/{mspId}/customAttributes/{partnerAttributeId}/assignedEntities/search";
	public String GET_ASSIGNED_ENTITIES_BY_ATTRIBUTE_CLIENT="/tenants/{clientId}/customAttributes/{clientAttributeId}/assignedEntities/search";
	public String GET_PARTNER_ASSIGNED_ATTRIBUTES="/serviceProvider/partners/{mspId}/customAttributes";
	public String GET_CLIENT_ASSIGNED_ATTRIBUTES="/tenants/{mspId}/clients/{clientId}/customAttributes";
	public String GET_DEVICE_ASSIGNED_ATTRIBUTES="/tenants/{clientId}/devices/{resourceId}/customAttributes";
	public String UNASSIGN_DEVICES_FROM_CUSTOM_ATTRIBUTE="/tenants/{clientId}/customAttributes/{clientAttributeId}/values/{clientAttributeValueId}/devices";
	public String UNASSIGN_CLIENTS_FROM_CUSTOM_ATTRIBUTE="/tenants/{mspId}/customAttributes/{partnerAttributeId}/values/{partnerAttributeValueId}/clients";
	public String UNASSIGN_PARTNERS_FROM_CUSTOM_ATTRIBUTE="/serviceProvider/customAttributes/{spAttributeId}/values/{spAttributeValueId}/partners";
	
	public String SEARCH_NON_MONITORABLE_RESOURCES = "/tenants/{clientId}/integrations/installed/{installedIntgId}/resources/nonMonitorable/search";
	public String UPDATE_INSTALLED_INTEGRATION = "/tenants/{clientId}/integrations/installed/{installedIntgId}";
	public String CREATE_ESCALATION_POLICY="/tenants/{clientId}/escalations";
	public String GET_ESCALATION_POLICY="/tenants/{clientId}/escalations/{id}";
	public String UPDATE_ESCALATION_POLICY="/tenants/{clientId}/escalations/{id}";
	public String DELETE_ESCALATION_POLICY = "/tenants/{clientId}/escalations/{id}";
	public String DISABLE_ESCALATION_POLICY = "/tenants/{clientId}/escalations/{id}/{status}";
	public String GET_ESCALATION_POLICY_BY_ALERTID = "/tenants/{clientId}/alerts/{alertid}/escalations";
	public String SEARCH_ESCALATION_POLICY = "/tenants/{clientId}/escalations/search";
	public String ENABLE_ESCALATION_POLICY="/tenants/{clientId}/escalations/{id}/{status}";
	public String OBSERVED_ESCALATION_POLICY="/tenants/{clientId}/escalations/{id}/{status}";
	
	public String ASSIGN_CHILDS_GROUP="/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs";
	public String UNASSIGN_CHILDS_GROUP="/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs";
	public String GET_MINIMAL_DEVICE_GROUP="/tenants/{clientId}/deviceGroups/minimal";
	public String GET_ROOT_DEVICE_GROUP="/tenants/{clientId}/deviceGroups/search";
    public String GET_DEVICE_GROUP_CHILD = "/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs/search";
    public String INSTALL_NEWRELIC_INTEGRATION = "/tenants/{clientId}/integrations/install/NEWRELIC";
    public String INSTALL_PINGDOM_INTEGRATION = "/tenants/{clientId}/integrations/install/PINGDOM";
    
    public String CREATE_ALERT="/tenants/{clientId}/alert";
   	public String GET_ALERT =  "/tenants/{clientId}/alerts/{alertId}";
   	public String SEARCH_ALERT = "/tenants/{clientId}/alerts/search";
   	public String POST_ALERT_ACTION= "/tenants/{clientId}/alerts/{alertId}/actions/{action}";
   	public String GET_ALERT_SUBTYPES = "/tenants/{clientId}/subAlertTypes";
   	public String GET_ALERTS_BY_INCIDENT_ID = "/alerts/tenants/{clientId}/tickets/{ticketId}";
   	public String GET_ALERT_BY_ALERTID="/alerts/tenants/{clientId}/alerts/{alertId}";
   	public String GET_ALERT_COMMENTS = "/tenants/{clientId}/alerts/{alertId}/comments";
   	public String ATTACH_INCIDENT_TO_ALERT =  "/tenants/{clientId}/alerts/{alertId}/incidents/{IncidentId}/attach";
   	public String GET_ALERT_VIEW_OF_USER="/tenants/{clientId}/users/{userId}/alertViews";
   	public String GET_ALERT_STATUS_HISTORY="/tenants/{clientId}/alertStatusHistory/{alertId}";
   	public String ACKNOLEDGE_ALERT = "/tenants/{clientId}/alerts/{alertId}/acknowledge";
   	public String CREATE_ALERTS = "/tenants/{clientId}/alert";
   	public String UPDATE_ALERT_WITH_INCIDENT="/tenants/{clientId}/alerts/{alertId}/tickets/{ticketId}/update";
   	public String GET_ALERT_TYPES =  "/alertTypes";
   	public String CREATE_AWS_DISCOVERY_PROFILE="/tenants/{clientId}/policies/discovery";
   	public String CREATE_FIRST_RESPONSE_POLICY="/tenants/{clientId}/policies/firstResponse";
	public String GET_FIRST_RESPONSE_POLICY="/tenants/{clientId}/policies/firstResponse/{policyId}";
	public String DELETE_FIRST_RESPONSE_POLICY="/tenants/{clientId}/policies/firstResponse/{policyId}";
	public String ENABLE_DISABLE_OBSERVED_FIRST_RESPONSE_POLICY="/tenants/{clientId}/policies/firstResponse/{policyId}/{status}";
	public String GET_FIRST_RESPONSE_POLICY_BY_CLIENT="/tenants/{clientId}/policies/firstResponse/";
	public String UPDATE_FIRST_RESPONSE_POLICY="/tenants/{clientId}/policies/firstResponse/{policyId}";
	public String NEW_CREATE_DEVICE_GROUP="/tenants/{clientId}/deviceGroups";
	public String NEW_GET_DEVICE_GROUP="/tenants/{clientId}/deviceGroups/{deviceGroupId}";
	public String NEW_UPDATE_DEVICE_GROUP="/tenants/{clientId}/deviceGroups";
	public String NEW_DELETE_DEVICE_GROUP="/tenants/{clientId}/deviceGroups/{deviceGroupId}";
	public String NEW_ASSIGN_CHILDS_GROUP="/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs";
	public String NEW_UNASSIGN_CHILDS_GROUP="/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs";
	public String NEW_GET_DEVICE_GROUP_CHILD="/tenants/{clientId}/deviceGroups/{deviceGroupId}/childs/search";
	public String NEW_GET_MINIMAL_DEVICE_GROUP="/tenants/{clientId}/deviceGroups/minimal";
	public String NEW_GET_ROOT_DEVICE_GROUP="/tenants/{clientId}/deviceGroups/search";
	
	public String GET_DEVICE_GROUPS = "/tenants/{clientId}/policies/deviceGroups";
	public String GET_MINIMAL_DEVICE_GROUPS = "/tenants/{clientId}/deviceGroups/minimal";
	public String SEARCH_DEVICE_GROUPS = "/tenants/{clientId}/policies/deviceGroups/search";

	public String CREATE_DEVICE_GROUP="/tenants/{clientId}/policies/deviceGroups";
	public String GET_DEVICE_GROUP = "/tenants/{clientId}/policies/deviceGroups/{deviceGroupId}";

	public String DELETE_DEVICE_GROUP="/tenants/{clientId}/policies/deviceGroups/{deviceGroupId}";
	public String UPDATE_DEVICE_GROUP = "/tenants/{clientId}/policies/deviceGroups";
	
	public String GET_LIST_OF_INTERFACES_PER_DEVICE="/tenants/{clientId}/topology/resourceInterfaces";
	public String GET_LIST_OF_UNMANAGED_DEVICES="/tenants/{clientId}/topology/unmanagedDevices";
	public String GET_LIST_OF_VLAN_AVAILABLE_FOR_DEVICE="/tenants/{clientId}/topology/availableVLAN";
	public String GET_LIST_OF_VERTICES_BY_EDGEPROPERTY="/tenants/{clientId}/topology/edgeVertices?edgeProperty=srcInt:";
	public String GET_NEIGHBOURS_OF_GIVEN_DEVICE="/tenants/{clientId}/topology/neighbours";

	public String GET_TOPOLOGY_BY_RESOURCEID="/tenants/{clientId}/topology/topologyByResourceId";
	public String GET_TOPOLOGY_DATA_BY_IPADDRESS="/tenants/{clientId}/topology/topologyInfo";
	
	public String GET_SERVICE_CATALOG_CATEGORY="/tenants/{clientId}/serviceCatalogs/categories/{categoryId}";
	public String UPDATE_SERVICE_CATALOG_CATEGORY="/tenants/{clientId}/serviceCatalogs/categories/{categoryId}";
	public String DELETE_SERVICE_CATALOG_CATEGORY="/tenants/{clientId}/serviceCatalogs/categories/{categoryId}";
    
    
	
	
	/***
	 * The below APIs are about mobile API
	 */
		public String FEEDBACK="/feedback";
		public String FORGOT_PASSWORD="/basic/auth/forgotPassword";
		public String GET_ALERT_FILTER_DATA="basic/tenants/{tenantId}/alertViews/{id}";
		public String GET_ALERTS_COUNT="basic/tenants/{tenantId}/alerts/count";
		public String GET_DEVICES_COUNT="basic/tenants/{tenantId}/devices/count";
		public String GET_INCIDENTS_COUNT="basic/tenants/{tenantId}/incidents/count";
		public String GET_THEME_AND_SSO_DETAILS="basic/auth/subdomain/{subDomain}";
		public String HOME_VIEW_DETAILS="basic/home/details";
		public String LOGIN="basic/auth/login";
		public String LOGOUT="basic/auth/signout";
		public String MENU_DETAILS="basic/menu/details";
		public String REGISTER_2_FACTOR_AUTHENTICATION="basic/auth/twoFactor/{provider}/register";
		public String VALIDATE_2_FACTOR_AUTHENTICATION="basic/auth/twoFactor/{provider}/validate";
		public String ACTIVATE_OR_DEACTIVATE_CLIENT = "/tenants/{varId}/clients/{clientId}/{action}";
		public String GET_MINIMAL_CLIENTS = "/tenants/{varId}/clients/minimal";
		public String UPDATE_CLIENT = "/tenants/{varId}/clients/{clientId}";
		public String DOWNLOAD_REPORT = "/tenants/{tenantId}/reports/download/id/{uuid}/filename/{filename}";
		public String CREATE_MON_TEMPLATES="/monitoring/templates/create?scope={scope}";
		public String GET_MON_TEMPLATES="/monitoring/templates";
		public String SEARCH_MON_TEMPLATES="/tenants/{tenantId}/monitoring/templates/search";
		
		
		public String CREATE_ALERT_CORRELATION_POLICY="/tenants/{tenantId}/policies/alertCorrelation";
		public String DELETE_ALERT_CORRELATION_POLICY="/tenants/{tenantId}/policies/alertCorrelation/{policyId}";
		public String ENABLE_DISABLE_ALERT_CORRELATION_POLICY="/tenants/{tenantId}/policies/alertCorrelation/{policyId}/{status}";
		public String GET_ALERT_CORRELATION_POLICY_CLIENT="/tenants/{tenantId}/policies/alertCorrelation/";
		public String GET_ALERT_CORRELATION_POLICY="/tenants/{tenantId}/policies/alertCorrelation/{policyId}";
		public String UPDATE_ALERT_CORRELATION_POLICY="/tenants/{tenantId}/policies/alertCorrelation/{policyId}";
			
}
